import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Award, Download, CheckCircle } from "lucide-react";
import { toast } from "sonner";

interface EligibilityCertificateProps {
  websiteUrl: string;
  overallScore: number;
  date: string;
}

export const EligibilityCertificate = ({ websiteUrl, overallScore, date }: EligibilityCertificateProps) => {
  const generateCertificate = () => {
    const certificateContent = `
╔══════════════════════════════════════════════════════════════╗
║                                                              ║
║              GOOGLE ADSENSE ELIGIBILITY CERTIFICATE          ║
║                                                              ║
╚══════════════════════════════════════════════════════════════╝

                    🏆 CERTIFICATE OF ELIGIBILITY 🏆

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

This is to certify that the website:

                    ${websiteUrl}

Has successfully passed the AdSense Eligibility Check with a score of:

                        ${overallScore}/100 ✓

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

VERIFICATION DETAILS:
• Date of Assessment: ${new Date(date).toLocaleDateString()}
• Verification ID: ${Date.now().toString(36).toUpperCase()}
• Status: ELIGIBLE FOR ADSENSE APPLICATION

PASSED CRITERIA:
✓ Domain meets age requirements
✓ SSL certificate properly configured
✓ Sufficient high-quality content
✓ Original and compliant content
✓ Mobile-responsive design
✓ Acceptable page load speed
✓ Privacy policy implemented
✓ Clear navigation structure

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

NEXT STEPS:
1. Apply for Google AdSense at: google.com/adsense
2. Keep your content quality high and update regularly
3. Maintain compliance with AdSense policies
4. Monitor your site's performance metrics

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Note: This certificate indicates eligibility based on technical
requirements. Final approval is at Google's discretion.

Generated by AdSense Eligibility Checker
${new Date(date).toLocaleString()}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    `;

    const blob = new Blob([certificateContent], { type: "text/plain" });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `adsense-certificate-${websiteUrl.replace(/[^a-z0-9]/gi, "-")}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    window.URL.revokeObjectURL(url);
    
    toast.success("Certificate downloaded successfully!");
  };

  if (overallScore < 80) {
    return null;
  }

  return (
    <Card className="p-6 bg-gradient-to-br from-yellow-500/10 to-orange-500/10 border-yellow-500/30 overflow-hidden relative">
      {/* Decorative elements */}
      <div className="absolute top-0 right-0 w-32 h-32 bg-gradient-primary opacity-10 rounded-full blur-3xl" />
      <div className="absolute bottom-0 left-0 w-32 h-32 bg-gradient-accent opacity-10 rounded-full blur-3xl" />
      
      <div className="relative z-10">
        <div className="flex items-center gap-3 mb-4">
          <div className="p-3 rounded-full bg-gradient-to-br from-yellow-500 to-orange-500">
            <Award className="h-6 w-6 text-white" />
          </div>
          <div>
            <h3 className="text-xl font-bold">Eligibility Certificate</h3>
            <p className="text-sm text-muted-foreground">Congratulations! You've passed all checks</p>
          </div>
        </div>

        <div className="bg-card/50 backdrop-blur-sm rounded-xl p-6 border border-yellow-500/20 mb-4">
          <div className="flex items-center justify-center mb-4">
            <div className="relative">
              <div className="w-24 h-24 rounded-full bg-gradient-to-br from-yellow-500 to-orange-500 flex items-center justify-center">
                <CheckCircle className="h-12 w-12 text-white" />
              </div>
              <div className="absolute -top-2 -right-2 w-8 h-8 rounded-full bg-green-500 flex items-center justify-center border-4 border-card">
                <CheckCircle className="h-4 w-4 text-white" />
              </div>
            </div>
          </div>

          <div className="text-center mb-6">
            <p className="text-2xl font-bold mb-2">VERIFIED ELIGIBLE</p>
            <p className="text-4xl font-black bg-gradient-to-r from-yellow-600 to-orange-600 bg-clip-text text-transparent">
              {overallScore}/100
            </p>
            <p className="text-sm text-muted-foreground mt-2">{websiteUrl}</p>
          </div>

          <div className="grid grid-cols-2 gap-4 text-center text-sm">
            <div>
              <p className="text-muted-foreground">Verified On</p>
              <p className="font-semibold">{new Date(date).toLocaleDateString()}</p>
            </div>
            <div>
              <p className="text-muted-foreground">Verification ID</p>
              <p className="font-semibold">{Date.now().toString(36).toUpperCase()}</p>
            </div>
          </div>
        </div>

        <Button 
          onClick={generateCertificate}
          className="w-full bg-gradient-to-r from-yellow-600 to-orange-600 hover:from-yellow-700 hover:to-orange-700"
        >
          <Download className="mr-2 h-4 w-4" />
          Download Certificate
        </Button>

        <p className="text-xs text-muted-foreground text-center mt-4">
          Share this certificate to showcase your website's AdSense readiness
        </p>
      </div>
    </Card>
  );
};
